#.github/workflows/main.yml
name: CI1

on:
  pull_request:
    branches:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - run: |
         xcoderun -list
